# Generated by Django 3.1.6 on 2021-05-18 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=250, null=True, unique=True)),
                ('image', models.ImageField(null=True, upload_to='article/')),
                ('short_description', models.CharField(max_length=700)),
                ('long_description', models.CharField(max_length=1400)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('code', models.CharField(max_length=50)),
                ('video_link', models.FileField(default='default_link', upload_to='')),
                ('image_link', models.URLField(default='default_link')),
                ('long_description', models.TextField()),
                ('course_type', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(default='default.jpg', upload_to='')),
                ('address', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=13)),
                ('contact_no', models.CharField(max_length=12)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_users.user')),
            ],
        ),
        migrations.CreateModel(
            name='TblSectionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('image', models.ImageField(default='default.jpg', upload_to='')),
                ('contact_no', models.CharField(max_length=12)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.schoolmodel')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_users.user')),
            ],
        ),
        migrations.CreateModel(
            name='TblClassModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.schoolmodel')),
            ],
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('reg_no', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('password_at_time_of_creation', models.CharField(max_length=100)),
                ('imagepath', models.ImageField(default='default.jpg', upload_to='')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique=True)),
                ('section_id', models.CharField(max_length=12)),
                ('contact_no', models.CharField(max_length=12)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.schoolmodel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_users.user')),
            ],
        ),
        migrations.CreateModel(
            name='RoomModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=250, null=True, unique=True)),
                ('short_description', models.CharField(max_length=700)),
                ('long_description', models.CharField(max_length=1400)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.studentmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Enroll_StudentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollStudents', to='adminapp.tblclassmodel')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.coursemodel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.studentmodel')),
            ],
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='classes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tblclassmodel'),
        ),
        migrations.CreateModel(
            name='ContactFormModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('response', models.TextField(default='None')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('response_submitted', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.studentmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=250, null=True, unique=True)),
                ('short_description', models.CharField(max_length=700)),
                ('long_description', models.CharField(max_length=1400)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.studentmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ClientFeedBackModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('rating', models.CharField(choices=[('Good', 'Good'), ('Average', 'Average'), ('Bad', 'Bad')], default='none', max_length=100)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='adminapp.studentmodel')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='adminapp.coursemodel')),
            ],
        ),
        migrations.CreateModel(
            name='Assign_TeacherModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignclasses', to='adminapp.tblclassmodel')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigncourses', to='adminapp.coursemodel')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignteachers', to='adminapp.teachermodel')),
            ],
        ),
        migrations.CreateModel(
            name='AnnouncementModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=250, null=True, unique=True)),
                ('short_description', models.CharField(max_length=700)),
                ('long_description', models.CharField(max_length=1400)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tblclassmodel')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.schoolmodel')),
            ],
        ),
    ]
