# Generated by Django 3.1.6 on 2021-05-20 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientComplainModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('complain', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.clientmodel')),
            ],
        ),
        migrations.RemoveField(
            model_name='announcementmodel',
            name='class_id',
        ),
        migrations.RemoveField(
            model_name='announcementmodel',
            name='school',
        ),
        migrations.AlterField(
            model_name='clientfeedbackmodel',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='client.clientmodel'),
        ),
        migrations.CreateModel(
            name='SubmitClientComplainModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_submit', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('complain_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ClientComplainModel', to='adminapp.clientcomplainmodel')),
            ],
        ),
    ]
