# Generated by Django 3.1.6 on 2021-05-24 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_auto_20210521_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='class_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='adminapp.tblclassmodel'),
        ),
    ]
