# Generated by Django 3.1.6 on 2021-05-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_studentmodel_class_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='class_id',
            field=models.CharField(max_length=12),
        ),
    ]
