# Generated by Django 3.1.6 on 2021-05-25 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_auto_20210524_1509'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleModel',
        ),
    ]
