# Generated by Django 3.2 on 2021-07-12 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_users', '0002_user_is_parent'),
        ('adminapp', '0006_delete_articlemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('password_at_time_of_creation', models.CharField(max_length=100)),
                ('imagepath', models.ImageField(default='default.jpg', upload_to='')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique=True)),
                ('contact_no', models.CharField(max_length=12)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_users.user')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.schoolmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Enroll_ParentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.parentmodel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.studentmodel')),
            ],
        ),
    ]
