# Generated by Django 3.2 on 2021-07-12 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_enroll_parentmodel_parentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='enroll_parentmodel',
            name='classes',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollParent', to='adminapp.tblclassmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enroll_parentmodel',
            name='course',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.coursemodel'),
            preserve_default=False,
        ),
    ]
